spring:
  datasource:
    username: root
    password: anhhuy2003
    url: jdbc:mysql://localhost:3306/shop_ecommerce
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect